jobs:
  doctests:
    runs-on: self-hosted
    services:
      redis-stack:
        image: redis/redis-stack-server:latest
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout
          5s --health-retries 5
        ports:
        - 6379:6379
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Cache dependencies
      uses: actions/cache@v2
      with:
        key: jedis-${{hashFiles('**/pom.xml')}}
        path: '~/.m2/repository

          /var/cache/apt

          '
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Run doctests
      run: 'mvn -Pdoctests test

        '
name: Documentation Tests
on:
  repository_dispatch:
    types: trigger-ga___doctests.yml
