jobs:
  build:
    name: Build and Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up publishing to maven central
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: System setup
      run: 'sudo apt update

        sudo apt install -y stunnel make

        make system-setup

        '
    - continue-on-error: true
      name: Cache dependencies
      uses: actions/cache@v2
      with:
        key: jedis-${{hashFiles('**/pom.xml')}}
        path: '~/.m2/repository

          /var/cache/apt

          '
    - continue-on-error: true
      name: Maven offline
      run: 'mvn -q dependency:go-offline

        '
    - continue-on-error: true
      name: Build docs
      run: 'mvn javadoc:jar

        '
    - continue-on-error: true
      env:
        JVM_OPTS: -Xmx3200m
        TERM: dumb
      name: Run tests
      run: 'make test

        '
    - continue-on-error: true
      name: Codecov
      run: 'bash <(curl -s https://codecov.io/bash)

        '
name: Integration
on:
  repository_dispatch:
    types: trigger-ga___integration.yml
