jobs:
  snapshot:
    name: Deploy Snapshot
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up publishing to maven central
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '8'
        server-id: ossrh
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Cache dependencies
      uses: actions/cache@v2
      with:
        key: jedis-${{hashFiles('**/pom.xml')}}
        path: '~/.m2/repository

          /var/cache/apt

          '
    - continue-on-error: true
      name: mvn offline
      run: 'mvn -q dependency:go-offline

        '
    - continue-on-error: true
      env:
        MAVEN_PASSWORD: ${{secrets.OSSH_TOKEN}}
        MAVEN_USERNAME: ${{secrets.OSSH_USERNAME}}
      name: deploy
      run: "mvn --no-transfer-progress \\\n  -DskipTests deploy\n"
name: Publish Snapshot
on:
  repository_dispatch:
    types: trigger-ga___snapshot.yml
