jobs:
  check-spelling:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Check Spelling
      uses: rojopolis/spellcheck-github-actions@0.33.1
      with:
        config_path: .github/spellcheck-settings.yml
        task_name: Markdown
name: spellcheck
on:
  repository_dispatch:
    types: trigger-ga___spellcheck.yml
