jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v3
      with:
        days-before-close: 30
        days-before-stale: 365
        operations-per-run: 10
        remove-stale-when-updated: false
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: stale
        stale-issue-message: This issue is marked stale. It will be closed in 30 days
          if it is not updated.
        stale-pr-label: stale
        stale-pr-message: This pull request is marked stale. It will be closed in
          30 days if it is not updated.
name: Close stale issues
on:
  repository_dispatch:
    types: trigger-ga___stale-issues.yml
permissions: {}
