jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      id: get_version
      name: get version from tag
      run: 'realversion="${GITHUB_REF/refs\/tags\//}"

        realversion="${realversion//v/}"

        echo "VERSION=$realversion" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: Set up publishing to maven central
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '8'
        server-id: ossrh
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: mvn versions
      run: mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}
    - continue-on-error: true
      name: Install gpg key
      run: 'cat <(echo -e "${{ secrets.OSSH_GPG_SECRET_KEY }}") | gpg --batch --import

        gpg --list-secret-keys --keyid-format LONG

        '
    - continue-on-error: true
      env:
        MAVEN_PASSWORD: ${{secrets.OSSH_TOKEN}}
        MAVEN_USERNAME: ${{secrets.OSSH_USERNAME}}
      name: Publish
      run: "mvn --no-transfer-progress \\\n  --batch-mode \\\n  -Dgpg.passphrase='${{\
        \ secrets.OSSH_GPG_SECRET_KEY_PASSWORD }}' \\\n  -DskipTests deploy -P release\n"
name: Release
on:
  repository_dispatch:
    types: trigger-ga___version-and-release.yml
